---
- hosts: all
  become: true
  vars_files:
    - ./vars/defaults.yaml
    - ./vars/gslt.yaml

  #roles:
  #  - cloudalchemy.node_exporter

  tasks:
    - name: add i386 arch
      command: dpkg --add-architecture i386

    - name: Ensure LGSM Server Group exists
      group:
        name: "{{ lgsm_group }}"
        system: true

    - name: Ensure LGSM Server user exists
      user:
        name: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"
        shell: /bin/bash
        system: true

    - name: update home folder perms
      file:
        path: /home/{{ lgsm_user }}
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"
        state: directory
        recurse: true

    - name: update packages
      apt:
        upgrade: true
        update_cache: true

    - name: "Check if SteamCMD is installed"
      package_facts:
        manager: apt

    - name: SteamCMD (licence agreement)
      shell:
        cmd: echo steam steam/question select "I AGREE" | sudo debconf-set-selections
      when: "'steamcmd:i386' not in ansible_facts.packages"

    - name: SteamCMD (licence note)
      shell:
        cmd: echo steam steam/license note '' | sudo debconf-set-selections
      when: "'steamcmd:i386' not in ansible_facts.packages"

    - name: Install LGSM dependencies
      apt:
        name: "{{ item }}"
      loop: "{{ lgsm_dependencies }}"

    - name: Download LGSM server creator
      get_url:
        url: https://linuxgsm.sh
        dest: "/home/{{ lgsm_user }}/linuxgsm.sh"
        mode: 0755
        owner: "{{ lgsm_user }}"

    - name: check if tf2server file exists
      stat:
        path: "/home/{{ lgsm_user }}/tf2server"
      register: tf2server_file

    - name: Initialize the tf2server
      command: ~/linuxgsm.sh tf2server
      args:
        chdir: "/home/{{ lgsm_user }}"
      become_user: "{{ lgsm_user }}"
      register: tf2server_init
      when: not tf2server_file.stat.exists

    - name: Installing the tf2server(this step might take 30-40min)
      shell: ~/tf2server auto-install > tf2install.log
      args:
        executable: /bin/bash
        chdir: "/home/{{ lgsm_user }}"
      become_user: tf2server
      when: not tf2server_file.stat.exists

    - name: Copy server configuration
      template:
        src: files/tf2server.cfg.j2
        dest: /home/{{ lgsm_user }}/serverfiles/csgo/cfg/tf2server.cfg
        mode: 0755
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"

    - name: Copy lgsm configuration
      template:
        src: files/lgsm-tf2server.cfg.j2
        dest: /home/{{ lgsm_user }}/lgsm/config-lgsm/tf2server/tf2server.cfg
        mode: 0755
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"

    - name: make addons folder
      file:
        path: /home/{{ lgsm_user }}/serverfiles/csgo/addons
        state: directory
        mode: 0755
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"

    - name: make temp download folder
      file:
        path: /home/{{ lgsm_user }}/temp
        state: directory
        mode: 0755
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"

    - name: unarchive get5
      unarchive:
        src: https://github.com/splewis/get5/releases/download/v0.12.0/get5-v0.12.0.zip
        dest: /home/{{ lgsm_user }}/serverfiles/csgo
        remote_src: true

    - name: remove license
      file:
        path: /home/{{ lgsm_user }}/serverfiles/LICENSE
        state: absent

    - name: remove readme
      file:
        path: /home/{{ lgsm_user }}/serverfiles/README.md
        state: absent

    - name: download metamod
      unarchive:
        src: https://mms.alliedmods.net/mmsdrop/1.11/mmsource-1.11.0-git1148-linux.tar.gz
        dest: /home/{{ lgsm_user }}/serverfiles/csgo
        remote_src: true

    - name: download sourcemod
      unarchive:
        src: https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6928-linux.tar.gz
        dest: /home/{{ lgsm_user }}/serverfiles/csgo
        remote_src: true

    - name: download steamworks
      unarchive:
        src: https://github.com/KyleSanderson/SteamWorks/releases/download/1.2.3c/package-lin.tgz
        dest: /home/{{ lgsm_user }}/temp
        remote_src: true

    - name: copy steamworks
      copy:
        src: /home/{{ lgsm_user }}/temp/package/addons
        dest: /home/{{ lgsm_user }}/serverfiles/csgo
        mode: 0755
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"
        remote_src: true

    - name: copy admins file
      copy:
        src: files/admins_simple.ini
        dest: /home/{{ lgsm_user }}/serverfiles/csgo/addons/sourcemod/configs/admins_simple.ini
        mode: 0755
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"
      register: csgoadmins

    - name: download pugsetup
      unarchive:
        src: https://github.com/splewis/csgo-pug-setup/releases/download/2.0.7/pugsetup_2.0.7.zip
        dest: /home/{{ lgsm_user }}/serverfiles/csgo
        remote_src: true

    - name: Fix file permissions
      file:
        path: /home/{{ lgsm_user }}
        owner: "{{ lgsm_user }}"
        group: "{{ lgsm_group }}"
        mode: 0755
        state: directory
        recurse: true

    - name: Restart the server
      become_user: "{{ lgsm_user }}"
      command: ~/tf2server restart
      args:
        chdir: "/home/{{ lgsm_user }}"
